version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: "@babel/*"
    versions:
    - ">= 0"
  - dependency-name: babel-plugin-preval
    versions:
    - ">= 3.0"
  - dependency-name: core-js
    versions:
    - ">= 0"
  - dependency-name: "@date-io/*"
    versions:
    - ">= 0"
  - dependency-name: jss-*
    versions:
    - ">= 0"
  - dependency-name: raw-loader
    versions:
    - ">= 0"
  - dependency-name: react-dom
    versions:
    - ">= 0"
  - dependency-name: react-is
    versions:
    - ">= 0"
  - dependency-name: react-test-renderer
    versions:
    - ">= 0"
  - dependency-name: tslint
    versions:
    - 5.x
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - ">= 0"
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: webpack
    versions:
    - 5.11.0
    - 5.25.1
    - 5.27.1
  - dependency-name: webpack-cli
    versions:
    - 4.3.1
    - 4.4.0
  - dependency-name: aws-sdk
    versions:
    - 2.820.0
  - dependency-name: dayjs
    versions:
    - 1.9.8
